export const AVATARS = [
  { key: "pineapple", name: "PINEAPPLE", emoji: "🍍" },
  { key: "apple", name: "APPLE", emoji: "🍎" },
  { key: "turtle", name: "TURTLE", emoji: "🐢" },
  { key: "grape", name: "GRAPE", emoji: "🍇" },
  { key: "watermelon", name: "WATERMELON", emoji: "🍉" },
  { key: "cherry", name: "CHERRY", emoji: "🍒" },
  { key: "lemon", name: "LEMON", emoji: "🍋" },
  { key: "mango", name: "MANGO", emoji: "🥭" },
] as const;

export type AvatarKey = (typeof AVATARS)[number]["key"];

// Questions are now generated by Gemini at game-start — no static bank needed.
// Keeping this export as an empty tuple so any imports don't break at compile time.
export const QUESTION_BANK = [] as const;

export const MAX_WORDS = 250;
export const TOTAL_ROUNDS = 3;

// Increase this to allow more human players per room (max 7, one avatar slot is reserved for the AI).
export const PLAYERS_PER_ROOM = 2;
